Feat/change the web link for icons or words
edenia/antelope-tools pull request #1073
Opened 2022-11-24 18:16 UTC by fvives99

### What does this PR do?

- Resolve #1009 

### Steps to test

See Block Producer card information

2022-11-29 15:32 UTC, AngeloCG97 requested changes

2022-11-29 15:32 UTC, AngeloCG97 commented on webapp/src/components/InformationCard/ProducerInformation.js
> +  console.log(info)
Please remove this console

2022-11-29 15:32 UTC, AngeloCG97 commented on webapp/src/components/InformationCard/ProducerInformation.js
> +                ></LaunchIcon>
Please change 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                ></LaunchIcon>
```
by 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                />
```

2022-11-29 15:32 UTC, AngeloCG97 commented on webapp/src/components/InformationCard/ProducerInformation.js
> +                ></LaunchIcon>
Please change 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                ></LaunchIcon>
```
by 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                />
```

2022-11-29 15:32 UTC, AngeloCG97 commented on webapp/src/components/InformationCard/ProducerInformation.js
> +                ></LaunchIcon>
Please change 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                ></LaunchIcon>
```
by 
```
<LaunchIcon
                  onClick={() => window.open(info?.ownership, '_blank')}
                  className={classes.clickableIcon}
                />
```

2022-11-29 20:23 UTC, AngeloCG97 approved these changes
LGTM

2022-11-30 14:20 UTC, AngeloCG97 approved these changes
LGTM

2022-11-30 17:05 UTC, merged

2022-11-30 17:34 UTC, Edwinjrc reviewed
LGTM